Milestone 2: Added Card grid layout
prg-04/My_Portfolio pull request #2
Opened 2023-03-24 05:26 UTC by prg-04

###I have done the following to reach this milestone:

- [ ] Added the card section using a grid-layout.
- [ ] Made the page to be responsive as well.

2023-03-24 06:16 UTC, shella12 requested changes
Hi @prg-04 , 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- All linters passed ✅ 
- Professional README.md ✅   
- Correct use of git flow ✅ 
- Correct use of semantic tags ✅ 
- Good commit history ✅ 
- Descriptive pull request ✅ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 06:16 UTC, shella12 commented on README.md
> +
- [ ] Great job 👍  using on using the [README template](https://github.com/microverseinc/readme-template) however I would suggest you add a few lines describing your project here in the about section, explaining project's objectives and its essential qualities. Think of it as the elevator pitch to amaze the recruiters 😉

2023-03-24 06:16 UTC, shella12 commented on index.html
> +    <script src="index.js"></script>
- [ ] Great job 👍 adding the work section however you should also include to `about us` section of the project as well as it is mentioned in the [requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md#project--requirements)

> - the "About myself" section (placed after the projects and before the contact form):

**About us section from Figma design Template:**

<img width="722" alt="Screenshot 2023-03-24 at 10 37 13 AM" src="https://user-images.githubusercontent.com/44798044/227435649-303fb6ca-db24-4df1-b3a0-78e8b3a2754e.png">

2023-03-24 06:16 UTC, shella12 commented on styles.css
> +}
- [ ] Please add a bit of padding in the `title `, `description `and `tech stack` of the project card to match the [figma design template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1-1471&t=bFO3LY97dTXnhgBF-0)

Figma design:

<img width="168" alt="Screenshot 2023-03-24 at 10 53 22 AM" src="https://user-images.githubusercontent.com/44798044/227436823-1bbf1050-66c5-4fd7-9278-b8282efe80cb.png">


Your deisgn:

<img width="283" alt="Screenshot 2023-03-24 at 10 53 10 AM" src="https://user-images.githubusercontent.com/44798044/227436892-f25f1ce6-aa5e-450f-ab09-a198904d8a02.png">

2023-03-24 06:16 UTC, shella12 commented on styles.css
> +}
- [ ] Please add more margin between the `title ` and the `hr` of the work section as it is the [project requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md#project--requirements) to stick to the  [figma design template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1-1471&t=bFO3LY97dTXnhgBF-0)
 as much as possible (e.g., font, colors, images, text, margins) 

> You must stick to the design as much as possible (e.g., font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

Figma design:

<img width="193" alt="Screenshot 2023-03-24 at 10 51 42 AM" src="https://user-images.githubusercontent.com/44798044/227437885-1a73227f-b60b-4c24-a7ca-5cd02f0dd656.png">

Your deisgn:

<img width="368" alt="Screenshot 2023-03-24 at 10 52 07 AM" src="https://user-images.githubusercontent.com/44798044/227437925-e1dfc03a-92ed-4078-82c1-cf69efa809c6.png">

2023-03-24 06:16 UTC, shella12 commented on styles.css
> +  display: flex;
- [ ] Please align `.placeholder` class using flex box as stated in the project requirement 

> In order to lay out the elements in "Works" section you should use CSS Grid and Flexbox combined (it is mandatory that you use both). Use CSS Grid in the main container that contains all of the cards and use Flexbox to lay out an individual card.

- [ ] Please add a bit more gap between the elements of the project card to match the [figma design template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1-1471&t=bFO3LY97dTXnhgBF-0) as per [requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md#project--requirements)

Figma design:

<img width="186" alt="Screenshot 2023-03-24 at 10 51 49 AM" src="https://user-images.githubusercontent.com/44798044/227438191-39b03f1f-c9b5-4b2a-aa91-f2707f70a400.png">

Your deisgn:


<img width="368" alt="Screenshot 2023-03-24 at 10 52 16 AM" src="https://user-images.githubusercontent.com/44798044/227438234-d89cb747-b96d-44fa-b5ff-aacdb0b51e00.png">

2023-03-25 16:08 UTC, amon-cofie approved these changes
Hi @prg-04 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights

🚀 No linter errors
🚀 Descriptive pull request
🚀 Good commit messages 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-25 16:29 UTC, merged